stop_words:
  - XPRESS
  - LEVAR
  - Agencia
  - Shopee
  - Soc
  - Separação
  - Correios
  - NF
  - Nome Legivel
  - Documento
  - DANFE
  - Envio
  - Expressa
  - Rastreio
  - Nota
  - Etiqueta
  - Simplificado
  - Saída
  - Peso
  - AMAZON
  - Loggi
  - SEDEX
  - Shein
  - Objeto
  - CEP
  - loja
  - Igreja
  - Assinatura
  - Contrato
  - supplements
  - growth
  - flex
  - Mercado
  - pet
  - cpf
  - cnpj
  - Data