stop_words:
  - XPRESS
  - LEVAR
  - Agencia
  - Shopee
  - Soc
  - Separação
  - Correios
  - Pedido
  - NF
  - Nome Legivel
  - Documento
  - DANFE
  - Volume
  - Envio
  - Recebimento
  - Confirmação
  - Expressa
  - Finalizado
  - Rastreio
  - Entrega
  - Etiqueta
  - Pacote
  - Simplificado
  - Saída
  - Peso
  - Pedido
  - Volume
  - AMAZON
  - Loggi
  - SEDEX
  - Shein
  - Objeto
  - CEP
  - loja
  - Igreja
  - Assinatura
  - Recebedor
  - Contrato
  - Produtos
  - supplements
  - growth
  - flex
  - Mercado
  - pet
